# Transsion Audio Configuration.
TRAN_AUDIO_DOLBY_SUPPORT = yes
TRAN_AUDIO_ALLDENOISE_SUPPORT = yes
TRAN_AUDIO_IGO_VPNR_SUPPORT = yes
TRAN_AUDIO_REC_AINR_SUPPORT = yes
TRAN_AUDIO_AW87XXX_SUPPORT = yes
TRAN_AUDIO_LVACFS_SUPPORT = yes
TRAN_AUDIO_KARAOKE_SUPPORT = yes
TRAN_AUDIO_ELLIPTIC_USND_SUPPORT = yes
TRAN_AUDIO_TYPEC_SUPPORT = yes
TRAN_AUDIO_WIRELESS_MICROPHONE_SUPPORT = yes
TRAN_AUDIO_FS1599N_SUPPORT = yes
